### ISSUE TITLE
Fix warning on "this.geometry.addAttribute( )"

### ISSUE THREAD

**Issue by Chrisbright10** [spite/THREE.MeshLine#107]
I get thousands of warnings saying
"THREE.BufferGeometry: .addAttribute() has been renamed to .setAttribute()"

this seems like it would be a quick fix and no longer flood my console with warnings. specifically lines 337 - 343...
        this.geometry.addAttribute( 'position', this.attributes.position );
	this.geometry.addAttribute( 'previous', this.attributes.previous );
	this.geometry.addAttribute( 'next', this.attributes.next );
	this.geometry.addAttribute( 'side', this.attributes.side );
	this.geometry.addAttribute( 'width', this.attributes.width );
	this.geometry.addAttribute( 'uv', this.attributes.uv );
	this.geometry.addAttribute( 'counters', this.attributes.counters );

**Comment by Chrisbright10** [comment]
I found out that it was the npm package that hasn't been updated to work with the fix that has already been done here. If you control the package, can you update that too please?

**Comment by Jeremboo** [comment]
You're right! The new release is still not available on npm...

@spite, can you do it? I don't have the permission to publish yet

**Comment by Jeremboo** [comment]
@Chrisbright10 It's done!
See the v1.2.1 => https://www.npmjs.com/package/three.meshline
