### ISSUE TITLE
Break changes between 1.2.0 and 1.2.1

### ISSUE THREAD

**Issue by chuxiaonan** [spite/THREE.MeshLine#110]
Didn't follow SemVer rules, which indicates that 
> Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.
(https://semver.org/#spec-item-6)

Changes incompatible with lower THREE(e.g. r90+) were thrown on version 1.2.1, which means a developer who depends on THREE r90, will leads an error and eventually gets a crash. They(changes between 1.2.0 and 1.2.1) SHOULD be considered as break changes which lead an increase MINOR(or above) version number.

**Comment by Jeremboo** [comment]
Makes sense, I'll fix that asap!

**Comment by chuxiaonan** [comment]
> Makes sense, I'll fix that asap!

Nice job! Really appreciate that. ^_^

**Comment by Jeremboo** [comment]
1.2.1 is now depreciated: https://www.npmjs.com/package/three.meshline/v/1.2.1
