### ISSUE TITLE
Can it be used in the old version of three.js (version: 71)?

### ISSUE THREAD

**Issue by pangzx1** [spite/THREE.MeshLine#111]
I would like to ask, is the THREE.MeshLine.js file you provided suitable for three.js (version: 71)? I want to try to add a custom wide line using the js file you provided, but I have encountered some problems. Below is my problem description and code:
My error:
[https://uploads.disquscdn.com/images/a491f1b744b734765c759dcbb46441c1265bf40d8befc7ffbd7a8f532a75d735.png](https://uploads.disquscdn.com/images/a491f1b744b734765c759dcbb46441c1265bf40d8befc7ffbd7a8f532a75d735.png)

My code:
[https://uploads.disquscdn.com/images/b63b84b276e1e716d9c5238bfe1886532a8bcdab432433960a8ac318fb24861a.png](https://uploads.disquscdn.com/images/b63b84b276e1e716d9c5238bfe1886532a8bcdab432433960a8ac318fb24861a.png)

**Comment by Jeremboo** [comment]
The THREE.MeshLine v1.0.1 is based on the three.js r73 and might work for you. But you will definitively have breaking changes with the latest 1.3.0 release and maybe the older too.

But I don't think your error is due to the library itself. It's hard to tell you more without any live demos.
