### ISSUE TITLE
in-range breaking change.

### ISSUE THREAD

**Issue by trusktr** [spite/THREE.MeshLine#113]
I've been using `"three.meshline": "^1.2.0"`. Today I blew away my `node_modules` and re-installed everything, and I got

```
Uncaught TypeError: this.setAttribute is not a function
    at MeshLine.process (THREE.MeshLine.js:303)
    at MeshLine.setPoints (THREE.MeshLine.js:124)
    at MeshLine.setGeometry (THREE.MeshLine.js:82)
```

On this line:

https://github.com/spite/THREE.MeshLine/blob/168f9b28a9cf1f123df874d2d253872cadfa209c/src/THREE.MeshLine.js#L303

So for now I had to pinned the version to 1.2 by removing the `^` from package.json.

**Comment by ryanking1809** [comment]
Are you using the latest version of three.js?

**Comment by ronakshethia** [comment]
how did u solved it ?

**Comment by Jeremboo** [comment]
Thanks for your comment!

When you are using `"three.meshline": "^1.2.0"`, the `^` indicates that you want to have any version that is greater than or equal to `1.2.0` and less than `2.0.0`. In our case, that means the version `1.3.0` will be installed. 

And `1.3.0` only support `three.js >= r117`. So maybe your three.js version was too old.

@ronakshethia 3 solutions are offering to you:
- Update your `package.json` with `"three.meshline": "~1.2.0"`.
- Update your `package.json` with `"three.meshline": "1.2.0"`.
- Update three.js with a version greater or equal to `r117`.
