### ISSUE TITLE
How dashArray works?

### ISSUE THREAD

**Issue by ahsan-sabir** [spite/THREE.MeshLine#128]
Coming from the svg world, I am trying to wrap my head around how the dashArray option works here.

Given the description in readme (**dashArray - the length and space between dashes. (0 - no dash)**), 
I was assuming that in a line of like 50 units, a dashArray of like 25 would mean 1 dash and 1 gap. But things seem to work differently here. How to accomplish this in THREE.MeshLine?

https://codesandbox.io/s/optimistic-snowflake-y62s0

**Comment by Jeremboo** [comment]
Hi there!

```javascript
const material = new MeshLineMaterial({
      color: "red",
      lineWidth: 1,
      dashArray: 1 / 50
    });
```

Gives you a combinaison of 50 dashes and 50 gaps and with the same size!

**Comment by ahsan-sabir** [comment]
Can I specify dashes and gaps in units like we do in svg in px, for example the dash of 12 units and gap of 6 units?

**Comment by Jeremboo** [comment]
The `dashArray` will divide the current length of your line by the number you want. For example `1 / 50` will give you 50 dashes + 50 gaps whatever le length of your line. So if you line = 100 units, 1 dash will be 1 unit for sure.

Now, we have the `dashRatio` property too. That will help you to get a different a size for your dash compared to the gap.
Following your needs (12 units for the dash, 6 units for the gap), the gap should be 1 / 3 of the dash. So you can use those values: 

<img width="1027" alt="Screen Shot 2021-02-07 at 8 26 04 PM" src="https://user-images.githubusercontent.com/6682092/107157146-ca8f8380-6982-11eb-8425-0d1bc0c26035.png">
