### ISSUE TITLE
WARNING: Multiple instances of Three.js being imported. 

### ISSUE THREAD

**Issue by liorGameDev** [spite/THREE.MeshLine#156]
![image](https://user-images.githubusercontent.com/15868082/211196923-5a6fda3c-7cae-4ad5-93b8-45fd8c33c238.png)

I get this error when trying to use three.meshline
I think it is because TTHREE.Meshline imports three.cjs and not three.module.js - is there a way to enforce three.meshline to import three.module.js?

**Comment by Zerhogi** [comment]
It looks like you can get rid of warning by adding alias in your webpack config, in this case your main three.js and three.js from meshline will be imported from the same place
```
const path = require('path');

module.exports = {
    resolve: {
        alias: {
            three: path.resolve(__dirname, 'node_modules/three')
        },
    },
};
```

**Comment by wellcaffeinated** [comment]
I ran into this too with vite. For anyone else with this problem:

```js
// vite.config.js
import { defineConfig } from 'vite'
import path from 'path'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [],
  resolve: {
    alias: {
      'three/examples': path.resolve(__dirname, 'node_modules/three/examples/'),
      three: path.resolve(__dirname, 'node_modules/three/build/three.module.js'),
    },
  },
})
```

**Comment by liorGameDev** [comment]
@wellcaffeinated 
Worked for me!
