### ISSUE TITLE
THREE.AdditiveAlphaBlending removed from three.js

### ISSUE THREAD

**Issue by Jared-Sprague** [spite/THREE.MeshLine#22]
Hello!
I notice in your README and some of your demos you recommend using THREE.AdditiveAlphaBlending if transperant = true.  However that blending mode has been removed from three.js.  Just FYI you might want to update your README and demo references to it.
Thanks for a great library!

**Comment by spite** [comment]
Fixed on https://github.com/spite/THREE.MeshLine/commit/3e302abe5eda75da509876061139645cbd4ca955. Thanks!
