### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by AndrewRayCode** [spite/THREE.MeshLine#28]
So package can work in modern JS builds

**Comment by AndrewRayCode** [comment]
Temporarily put in NPM under my own namespace https://www.npmjs.com/package/meshline-andrewray

**Comment by spite** [comment]
My main problem with publishing to npm is making the library work with require/commonjs/es6 modules/whatever is being used at the moment. Have you done all that work, or just published the library? And if you have, how?

**Comment by spite** [comment]
Right. But then the library can't be used with <script>

**Comment by AndrewRayCode** [comment]
You set up a separate build step to build the script version, with three shimmed as global, and make that script available to download. That way both parties (people who want to use it in modern JS builds, and people who want to use script tags) can have their cake and eat it too.

**Comment by AndrewRayCode** [comment]
That's what I do with https://github.com/AndrewRayCode/easing-utils for example.

**Comment by spite** [comment]
The whole idea of keeping a <script>able version is so people don't have to necessarily deal with build scripts. I think I'll try to do it -again- like other libraries i have. I think https://www.npmjs.com/package/three.equirectangular-to-cubemap for instance does the trick.

**Comment by AndrewRayCode** [comment]
The end user doesn't have to deal with a build script at all. The end user, if they want to use a script, just download the file you link to (like my easing utils demo). You (as a project maintainer) just have to automatically build the code and host it somewhere when you update to a new version. It's just one command to run when you're ready to push the newest script tag version.

**Comment by AndrewRayCode** [comment]
It looks like the way you will do it with EquirectangularToCubemap will work too!

**Comment by spite** [comment]
Ideally, I want to only have to maintain one source, that can work as regular script, include, require, what have you. I think i'm going to go with the same structure, and let webpack/rollup/browserify/megazord deal with the other syntaxes.

**Comment by AndrewRayCode** [comment]
Just to clarify, I only maintain one source as well. It's quite clean and easy to read and doesn't require wrapping IIFEs or checking for global variables or anything, and allows for clean specific uses in both script tags and npm. https://github.com/AndrewRayCode/easing-utils/blob/master/src/easing.js

**Comment by spite** [comment]
How do browsers interpret 'export'?

**Comment by AndrewRayCode** [comment]
They don't, as mentioned in the readme if someone wants to use a script tag, they use the version built for a script tag (http://andrewray.me/easing.js). The full install instructions are in the readme, for any type of module system.

For people using modern js builds like webpack/browserify, those tools know how to read code in node_modules and correctly build them into browser bundles.

I don't mean to spam and not sure if it's relevant here, but it took me a while to fully understand modern JS builds and how webpack works, when I finally figured it out I wrote http://blog.andrewray.me/webpack-when-to-use-and-why/ .

**Comment by AndrewRayCode** [comment]
I'm happy to set up a similar build step in a branch and submit a PR, if you wish.

**Comment by spite** [comment]
Ok, but i still think there's two sources there. For me, as soon as a source file is transpiled/compiled/turned into a different thing, it's a new source, and needs testing. That's what I meant by "having one source". 

Every library i've created, when it's come to turn into an npm package, there's a new way of doing it.  During this conversation I've updated the source, but if you can create a PR with a build script to show what should be done, it'd be very helpful!

**Comment by AndrewRayCode** [comment]
A "bundled" version by webpack or browserify of what have you is the same codebase and doesn't require additional testing. The boilerplate code and syntax is just massaged to make sure it will load on the correct platform.

There are multiple ways of bundling modern javascript, yes, but I don't think that's a reason not to learn any of those tools!

I will set up the PR with a build step.

**Comment by spite** [comment]
Could you check if this works as expected? https://www.npmjs.com/package/three.meshline

**Comment by AndrewRayCode** [comment]
Yup, appears to work fine!

**Comment by spite** [comment]
Sweet! I'd like to see that build script, anyway!
