### ISSUE TITLE
Three.js fragment shader error

### ISSUE THREAD

**Issue by bebensiganteng** [spite/THREE.MeshLine#30]
The demo emit this error, is this something that can be ignored?

`THREE.WebGLProgram: gl.getProgramInfoLog() WARNING: Output of vertex shader 'vPosition' not read by fragment shader`

**Comment by spite** [comment]
Fixed on https://github.com/spite/THREE.MeshLine/commit/47bb7f365c7ee3dd386c2dd825ba187de2ff2cd9 and updated.
