### ISSUE TITLE
how to set texture repeat in MeshLine

### ISSUE THREAD

**Issue by Simon-wu** [spite/THREE.MeshLine#31]
I want draw a path use this, and fill it with a arrow texture .
But i cannot set repeat model like >>>>>>>>>>>> layout。
can you tell  me  how to mapping like this，  stretch is not i want

thanks  thanks

**Comment by spite** [comment]
Just published a new version. The material has now a `repeat` uniform to set tiling. Hope it helps!

**Comment by Simon-wu** [comment]
@spite  Can show me a demo? Thanks  i don know how to  set it

**Comment by spite** [comment]
Sure, the documentation on the Read.me and the spinner example has been updated to show how repeat works
https://www.clicktorelease.com/code/THREE.MeshLine/demo/spinner.html
