### ISSUE TITLE
Updating MeshLineMaterials opacity

### ISSUE THREAD

**Issue by adamjamescuz** [spite/THREE.MeshLine#36]
Is it possible to update the mesh line material's opacity after it has been created? (e.g in an animation). I can set the opacity at the start using the the transparent:true and the opacity params as you describe but if I try to update the opacity at a later time using either meshlinematerial.opacity = whatever, or mesh.material.opacity neither of these work.

**Comment by spite** [comment]
Good catch, I'm not mirroring the values from the material wrapper into the shader.

For now, you can update the opacity -and other values- with the material uniforms directly:
```lineMesh.material.uniforms.opacity.value = whatever```

**Comment by adamjamescuz** [comment]
Great, thank you
