### ISSUE TITLE
How to draw a curve on a sphere

### ISSUE THREAD

**Issue by lishaobobo** [spite/THREE.MeshLine#41]
How to draw a curve on a sphere，thank you！

**Comment by makc** [comment]
Shouldn't you be able to draw a curve on anything by copy-pasting from [this](https://www.clicktorelease.com/code/THREE.MeshLine/demo/shape.html)?

**Comment by lishaobobo** [comment]
@makc now I know the beginning and the end and radius，but I can't control the direction of meshLine

**Comment by spite** [comment]
You have to build the array of vertices that define your curve. You can google how to create arcs: you need to turn your start and end points into spherical coordinates, and interpolate from one to the other, turning each interpolated point back to cartesian and add it to the MeshLine vertex array,

**Comment by lishaobobo** [comment]
@spite I've already solved it. Thank you！

**Comment by spite** [comment]
Great to know! How did you end up doing it?

**Comment by lishaobobo** [comment]
@spite As you say, first know the starting point, then use the ball coordinates, the most important time line radian
