### ISSUE TITLE
support Curve geometry

### ISSUE THREAD

**Issue by morandd** [spite/THREE.MeshLine#43]
I'm thinking to add suport for Curve geometry. Just adding something like

if (g instanceof Three.Curve)
  verticies = g.getSpacedPoints()

Any reactions/thoughts before I proceed?

**Comment by spite** [comment]
Sounds interesting! Where were you thinking the divisions value for the getSpacedPoints call should be specified?

**Comment by morandd** [comment]
hmm, good point.

My interest actually is in 
https://github.com/andreasplesch/aframe-meshline-component
which wraps this component. But maybe I will add the Curve interpolation there, since you're right I don't see a particularly convenient way to add it here.

**Comment by morandd** [comment]
in the end, adding all the Curve interpolation functionality to the aframe-meshline
