### ISSUE TITLE
Effected by fog

### ISSUE THREAD

**Issue by bravokiloecho** [spite/THREE.MeshLine#48]
Is there any way to get the lines to be effected by scene fog?

p.s. This is a fantastic tool and very useful, thank you!

**Comment by spite** [comment]
Not in the code, but there was this pull request: https://github.com/spite/THREE.MeshLine/pull/32
It's not easily mergeable any more, but you can ask @rahulpowar

**Comment by bravokiloecho** [comment]
Ok, thank you!
