### ISSUE TITLE
Wagner Doesnt like THREE.MeshLine 

### ISSUE THREAD

**Issue by Makio64** [spite/THREE.MeshLine#5]
Hi !

I get an error when I use it with... Wagner 
[GroupMarkerNotSet(crbug.com/242999)!:D00486D2F37F0000]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.

my render function is like that :
@renderer.autoClearColor = true
@composer.reset()
@composer.render( @scene, @camera )
for pass in @passes
	@composer.pass( pass )
@composer.toScreen()

I use the a simple code for the MeshLine ( following the step ni the README ) & no problem wihout wagner or wihout MeshLine but both together.. Bug oO

Did I do something wrong with wagner ?

**Comment by spite** [comment]
Seems to be working here, with both THREE.MeshLine and Wagner checked out from the repo. Can you post an example somewhere?

<img width="1440" alt="screen shot 2015-12-10 at 15 11 19" src="https://cloud.githubusercontent.com/assets/731885/11717365/65fbdccc-9f50-11e5-8e1e-3d82a0546310.png">

**Comment by Makio64** [comment]
Works well after restarting computer... not sure why I get this error early on, sorry!
