### ISSUE TITLE
Simple line behaving strangely

### ISSUE THREAD

**Issue by ffpetrovic** [spite/THREE.MeshLine#58]
I literally just copied the code from the README and this is what I got. 

https://jsfiddle.net/filipetrovic/ggnLaaqt/

Why is it not a line, but this weird half circle shape?

Thanks

**Comment by spite** [comment]
Check out the REQUIRED part of the [MeshLineMaterial section in the Readme](https://github.com/spite/THREE.MeshLine/blob/master/README.md#create-a-meshlinematerial).

**Comment by ffpetrovic** [comment]
Solved by setting sizeAttenuation to 0, but please look at the updated fiddle, there seems to be some fog involved, where you can't see the entire line, any ideas?

**Comment by ffpetrovic** [comment]
The issue was in the camera and it's viewing distance, I updated the fiddle.

Thanks for the help
