### ISSUE TITLE
Uncaught RangeError: Source is too large

### ISSUE THREAD

**Issue by madferro** [spite/THREE.MeshLine#62]
Hi all, I followed the instructions, to create a MeshLine, but when i try to run "setGeometry" the following error rises up:

**Uncaught RangeError: Source is too large**

The steps to create the MeshLine are the following.

var geometry = new THREE.Geometry();
var line = new MeshLine();
geometry.vertices.push(new THREE.Vector3(-100,0.1,34));
geometry.vertices.push(new THREE.Vector3(70,0.1,-54));
line.setGeometry( geometry );
material = new MeshLineMaterial({
	color:new THREE.Color("rgb(26, 188, 156)")
});
var mesh = new THREE.Mesh( geometry, material );

What am i doing wrong? I'm using THREE.js v84, Chrome 67.0.3396.99 on Mac OSX High Sierra.

Thank you very much!

**Comment by Hari-KrishnanV** [comment]
@madferro instead of `var mesh = new THREE.Mesh( geometry, material );`, please try `var mesh = new THREE.Mesh( line.geometry, material );`

**Comment by madferro** [comment]
Ok it works, thank you very much!
