### ISSUE TITLE
Depth Issue

### ISSUE THREAD

**Issue by ikrong** [spite/THREE.MeshLine#65]
when set renderer logarithmicDepthBuffer=true, there is a depth issue
meshline always on top of the box in the example!

```js
var renderer = new THREE.WebGLRenderer( { 
  antialias: true, 
  alpha: true,
  logarithmicDepthBuffer: true,
});
````

### eg:
https://codepen.io/ikrong/pen/gjELmB

**Comment by GiTasty** [comment]
Can confirm, I have the same issue.
