### ISSUE TITLE
Example to display Dashed Lines

### ISSUE THREAD

**Issue by satyan** [spite/THREE.MeshLine#66]
Do we have an example to display Dashed lines.. I see the three parameters in the MeshLineMaterial namely (dashArray, dashRatio and dashOffset), but am not able to provide right values to draw a dashed line.

Thanks for the amazing library.

**Comment by Jeremboo** [comment]
The dashed lines properties are already implemented in the demo part:

https://github.com/spite/THREE.MeshLine/blob/d15d05c93d45477245bb004ec0bedd9cbd17c181/demo/js/main.js#L26-L28

https://github.com/spite/THREE.MeshLine/blob/d15d05c93d45477245bb004ec0bedd9cbd17c181/demo/js/main.js#L166-L168

https://github.com/spite/THREE.MeshLine/blob/d15d05c93d45477245bb004ec0bedd9cbd17c181/demo/js/main.js#L60-L61

You can also see it usage in thoses codepen : 

- [Animated dashed lines](https://codepen.io/Jeremboo/pen/aVdxPw?editors=0010)
- [Sporatic Lines](https://codepen.io/Jeremboo/pen/BmxOyB?editors=0010)

**Comment by jimtang** [comment]
I found these two parameters are important to draw dash style:
 ```
transparent: true,
opacity: 1,
```
and these are attributes from base class `Material`, don NOT forget to set them!!!

**Comment by Jeremboo** [comment]
@satyan you can find a complete tutorial on Codrops: [Animated Mesh Lines](https://tympanus.net/codrops/2019/01/08/animated-mesh-lines/)

Updated thanks to @jimtang & @Mamboleoo who are hightlight the importance to set `transparent: true` into the material.
