### ISSUE TITLE
Update color dynamically possible of MeshLine?

### ISSUE THREAD

**Issue by AngeloETH** [spite/THREE.MeshLine#67]
I want to develop a method can change the color of MeshLine by 
listening the event from client like this: http://jsfiddle.net/ebeit303/Lfr5my2s/.
In the above case, the material is `THREE.LineBasicMaterial` in line29. In MeshLine, the material available is `MeshLineMaterial`.  However, I can't update color of `MeshLineMaterial` like example. Is it possible to update color dynamically using MeshLine?

**Comment by jimtang** [comment]
You can set the mesh's color directly like this:
`lineMesh.material.uniforms.color.value = new Color('red');`

**Comment by myleskeller** [comment]
> You can set the mesh's color directly like this:
> `lineMesh.material.uniforms.color.value = new Color('red');`

for anyone else that tried implementing this snippet but received `Failed to execute 'uniform3fv' on 'WebGLRenderingContext'` in the JS console, according to [this issue](https://github.com/spite/THREE.MeshLine/issues/39#issuecomment-298245413), the correct syntax is now:
`lineMesh.material.uniforms.color.value = new THREE.Color('red');`
