### ISSUE TITLE
MeshLineMaterial() quietly modifies the parameters object passed to it

### ISSUE THREAD

**Issue by dwtkns** [spite/THREE.MeshLine#70]
If I have some options that I pass to a MeshLineMaterial:

```
var opts = {
    color: 0xff0000,
    resolution: new THREE.Vector2(width, height),
    opacity: 0.5
}

var material = new MeshLineMaterial(options);
```

...after creating that material, `opts.opacity === undefined`.

It looks like these parameter deletions are to blame:

https://github.com/spite/THREE.MeshLine/blob/d15d05c93d45477245bb004ec0bedd9cbd17c181/src/THREE.MeshLine.js#L418-L434

**Comment by Jeremboo** [comment]
If you want update the opacity, you can do:
`material.uniforms.opacity.value = 0.5`
