### ISSUE TITLE
Problems remain： THREE.Ray: .at() target is now required

### ISSUE THREAD

**Issue by blksky** [spite/THREE.MeshLine#84]
Problems remain： THREE.Ray: .at() target is now required

**Comment by fengxianhua** [comment]
same case, is the library author no longer maintained?

**Comment by jneilliii** [comment]
Someone patched the code over here, I haven't tested yet.

https://github.com/Tankerxyz/THREE.MeshLine/blob/patch-1/src/THREE.MeshLine.js

**Comment by trusktr** [comment]
I'll be maintaining a TypeScript fork of this; it'll be inside of http://github.com/infamous/infamous once I post it up.

I'll port updates like this one to there.

One thing I need to add is an option for rounded ends.
