### ISSUE TITLE
where is MeshLineMaterial from?

### ISSUE THREAD

**Issue by lidaof** [spite/THREE.MeshLine#90]
Hi there,

wondering where is `MeshLineMaterial ` from?
seems not in three, I tried in MeshLine, but got error:

TypeError: three_meshline__WEBPACK_IMPORTED_MODULE_4__.MeshLine.MeshLineMaterial is not a constructor

**Comment by Jeremboo** [comment]
Hey, it should be imported from the library.
Try that:  `import { MeshLine, MeshLineMaterial } from 'three.meshline';
`

**Comment by lidaof** [comment]
Thank you!!
