### ISSUE TITLE
latest three uses setAttribute rather  than addAttribute

### ISSUE THREAD

**Issue by andreasplesch** [spite/THREE.MeshLine#95]
https://github.com/mrdoob/three.js/commit/764bc3dbbc57b696277b77e648be3857ca3e4b25

introduced setAttribute. addAttribute does not work anymore with latest three (which is also used by aframe).

**Comment by zachzeyuwang** [comment]
@spite It would be nice to merge this -- deprecation warnings make fps drop drastically.
