### ISSUE TITLE
Repository is unmaintained

### ISSUE THREAD

**Issue by eulertour** [spite/THREE.MeshLine#99]
This repo hasn't had a commit in over a year and even simple issues like #95 have been ignored.

This is a glaring issue with three.js as this project is the de facto solution for drawing lines that are simultaneously thick, curved, and transparent. Collaborators on three.js recommend this project regularly to address the shortcomings of their own line API [[1](https://github.com/mrdoob/three.js/issues/16964#issuecomment-507822935)][[2](https://github.com/mrdoob/three.js/pull/16570#issuecomment-497102814)].

Is there a better maintained fork of this repo, or an alternative that can take its place?

**Comment by makc** [comment]
you could check https://github.com/spite/THREE.MeshLine/network for your answer. from the look of things, axion014 fork is the most updated.

**Comment by trusktr** [comment]
I don't see @axion014's on there, but I do see a bunch of more recently-updated forks. I see some interesting commits like `added gradient functionality` which is super sweet.

There's a lot of changes across forks. I bet many of them might be conflict-free. I wish @github had a way to reconcile changes across forks into new forks.

**Comment by axion014** [comment]
I deleted my direct fork and am instead forking @ryanking1809's fork.

**Comment by ryanking1809** [comment]
Yes, I forked `THREE.meshline` for this reason https://github.com/ryanking1809/threejs-meshline happy to merge in any improvements you have!

**Comment by Jeremboo** [comment]
Hi guys, 

I've been added by The Spite as contributor to the project.
I'll do my best to make it alive again! 

So please feel free to do any other PR or recommendations!

**Comment by ryanking1809** [comment]
@Jeremboo good to hear! I've created a pull request with all the changes I've made, it's quite a big one as I've merged a few neglected forks and cleanup the api a bit.

Happy to work with you to merge it in. I'd rather it all be here than continue maintaining my own version.

**Comment by eulertour** [comment]
@Jeremboo Any update on this? Getting #102 merged would be a big help even if you got too busy to maintain the repo.
